name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 */10 * * *'  # Runs every 10 hours

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Empty Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keep awake"
          git push
